/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unitn.ds1;

import it.unitn.ds1.Replicas.types.Crash;
import it.unitn.ds1.SimulationController.SimulationController;


public class App {
        // to pass arbitrary arguments in gradle run --args='-c 3 -r 4'
        final private static int N_CLIENTS = 3;
        final private static int N_REPLICAS = 8;

        public static void main(String[] args) {
            int[] parsedArgs = parseArguments(args);
            int numberOfClients = parsedArgs[0];
            int numberOfReplicas = parsedArgs[1];

            //Crash[] crashes = Collections.nCopies(numberOfReplicas, Crash.NO_CRASH).toArray(new Crash[0]);
            Crash[] crashes = { Crash.NO_CRASH, Crash.NO_CRASH, Crash.NO_CRASH, Crash.NO_CRASH, Crash.NO_CRASH,
                    Crash.NO_CRASH, Crash.NO_CRASH, Crash.COORDINATOR_BEFORE_WRITEOK_MESSAGE };
            SimulationController simulationController = new SimulationController(numberOfClients, numberOfReplicas, crashes, "normal_run", false);

            simulationController.run();
        }

        private static int[] parseArguments(String[] args) {
            int numberOfClients = N_CLIENTS;
            int numberOfReplicas = N_REPLICAS;

            for (int i = 0; i < args.length; i++) {
                switch (args[i]) {
                    case "-c":
                        if (i + 1 < args.length) {
                            numberOfClients = Integer.parseInt(args[++i]);
                        }
                        break;

                    case "-r":
                        if (i + 1 < args.length) {
                            numberOfReplicas = Integer.parseInt(args[++i]);
                        }
                        break;

                    default:
                        System.out.println("Error: Unknown argument " + args[i]);
                        return null;
                }
            }

            return new int[] { numberOfClients, numberOfReplicas };
        }
}
